---
title: "demo_2"
author: "Theo Killian"
date: "July 1, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Plotting and visualising data

```{r library}
library(ggplot2)
```

## Base plotting

```{r}
plot(rnorm(100))
# base plot doesn't have any concept of "global" data. you have to point "over
# and over again" to this dataframe
```


```{r}
head(DNase)
```

```{r}
plot(DNase$con, DNase$density)
```

```{r}
plot(DNase$con, DNase$density,
     xlab = "DNase concentration (ng/ml)",
     ylab = "Optical density",
     pch = 1,
     col = "steelblue")
abline(v = unique(DNase$conc), lty = "dotted")
```

## The ggplot2 package

```{r}
ggplot(data = DNase, mapping = aes(x = conc, y = density)) + geom_point()
```

```{r}
gg <- ggplot(data = DNase, mapping = aes(x = conc, y = density)) + geom_point()
print(gg)
```

```{r}
gg + geom_point(aes(colour = Run))
```

```{r}
#microarray data
load("./hiiragi2013.rda")
library("Biobase")
dftx <- data.frame(t(Biobase::exprs(hiiragi2013)), pData(hiiragi2013))
dftx[1:10, 1:3]
# class(dftx)
# dim(dftx)
```

```{r}
dftx[1:10, 45105:45109]
```

```{r}
ggplot(dftx, aes(x = X1426642_at, y = X1418765_at)) +
    geom_point(aes(color = sampleColour))
```


```{r}
ggplot(dftx, aes(x = X1426642_at, y = X1418765_at)) +
    geom_point(shape = 1) +
    geom_smooth(method = "loess")
```

```{r}
ggplot(dftx, aes(x = X1426642_at, y = X1418765_at))  +
  geom_point(aes(color = sampleColour), shape = 19) +
  geom_smooth(method = "loess")
```

### Visualising 1D data

```{r}
selectedProbes <- c(Fgf4 = "1420085_at", Gata4 = "1418863_at",
                    Gata6 = "1425463_at",  Sox2 = "1416967_at")
hiiragi2013[selectedProbes, ]
```

```{r}
library("dplyr")
library("tidyr")
tmp <- data.frame(t(exprs(hiiragi2013[selectedProbes, ])))
names(tmp) <- names(selectedProbes)
tmp$sample <- rownames(tmp)
head(tmp)
```

```{r}
genes <- gather(tmp, key = "gene", value = "expression", -sample)
head(genes)
```

### Histogram

```{r}
genes %>% filter(gene == "Gata4") %>% ggplot(aes(x = expression)) +
    geom_histogram()
```

### Box plots

```{r}
p <- ggplot(genes, aes(x = gene, y = expression, fill = gene))
bxplot <- p + geom_boxplot()
bxplot
```

### Dot plots and beeswarm plots

```{r}
jtrplot <- p + geom_jitter(aes(colour = gene)) + theme(legend.position = "none")
```

```{r}
dotplot <- p + geom_dotplot(binaxis = "y", binwidth = 1/6,
                            stackdir = "center", stackratio = 0.75,
                            aes(color = gene)) +
    theme(legend.position = "none")
```

```{r}
library("ggbeeswarm")
beeplot <- p + geom_beeswarm(aes(color = gene)) + 
    theme(legend.position = "none")
```

```{r}
library(patchwork)
jtrplot + dotplot + beeplot
```

### Density and ecdf plots

```{r}
densplot <- ggplot(genes, aes(x = expression, color = gene)) +
    geom_density() +
    theme(legend.position = "none")
```

```{r}
ecdfplot <- ggplot(genes, aes(x = expression, color = gene)) +
    stat_ecdf() +
    theme(legend.position = "none")
```

```{r}
densplot + ecdfplot
```

### Summary

```{r}
sim <- data.frame(x = exp(rnorm(n = 1e5,
                                mean = sample(c(2, 5),
                                              size = 1e5,
                                              replace = TRUE))))
p1 <-  ggplot(sim, aes(x)) +
    geom_histogram(binwidth = 10, boundary = 0) +
    xlim(0, 400)
p2 <-  ggplot(sim, aes(log(x))) +
    geom_histogram(bins = 30)
p1 + p2
```

### Visualising 2D data

```{r}
dfx <- as.data.frame(Biobase::exprs(hiiragi2013))
scp <- ggplot(dfx, aes(x= `59 E4.5 (PE)`, 
                       y = `92 E4.5 (FGF4-KO)`)) 
scp + geom_point(alpha = 0.1)
```

```{r}
scp + geom_density2d(h = 0.5, bins = 60)
```

```{r}
scp + geom_hex() 
```

### Visualising data along more dimensions

```{r}
# p1 <- ggplot(dftx, aes(x = X1426642_at, y = X1418765_at, colour = lineage)) +
#   geom_point()
# p2 <- ggplot(dftx, aes(x = X1426642_at, y = X1418765_at)) +
#   geom_point() +
#     facet_grid( . ~ lineage )
# p1 + p2
```

```{r}
ggplot(dftx, aes(x = X1426642_at, y = X1418765_at)) +
    geom_point() +
    facet_grid( Embryonic.day ~ lineage )
```

### Interactive visualisation

```{r}
library("plotly")

scp <- ggplot(dfx[1:100, ], aes(x= `59 E4.5 (PE)`, y = `92 E4.5 (FGF4-KO)`))

scp2 <- scp + geom_point()
ggplotly(scp2)
```

```{r}
sessionInfo()
```