---
title: "demo_2"
author: "Theo Killian"
date: "July 1, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Practical: R/Bioconductor and Reproducible Research

```{r library}
library("readr")
library("dplyr")
```

```{r load_data}
pdata <- read_csv("~/tmp/summer_school/extdata/ALL-sample-sheet.csv")
head(pdata)
```

### Working with data (continued): exploration

```{r}
# pdata %>% arrange(age)
pdata %>% arrange(desc(age))
```

### summarize() and group_by()

```{r}
pdata %>% summarize(n = n())
```

```{r}
pdata %>% group_by(sex)
```

```{r}
pdata %>% group_by(sex) %>% summarize(n = n())
```

```{r}
pdata %>% 
    group_by(sex) %>% 
    summarize(n=n(), mean_age = mean(age, na.rm = TRUE))
```

### t.test(), an untidy function

```{r}
pdata %>% t.test(age ~ sex, data = .)
```

### filter() and %in%

```{r}
pdata %>%
    group_by(mol.biol) %>%
    count()
## group_by can be piped to summarize
```

```{r}
# c("a", "b", "c", "b", "a") %in% c("a", "c")
```

### Working with data (continued): Bioconductor objects

Create a short character vector of DNA sequences.

```{r}
library(Biostrings)
sequences <- c("AAATCGA", "ATACAACAT", "TTGCCA")
sequences
```

```{r}
length(sequences)
```

```{r}
nchar(sequences)
```

```{r}
sequences[c(1, 3)]
```

```{r}
sample(sequences)
```

```{r}
methods(class = "DNAStringSet")
```

### DNAStringSet()

```{r}
dna <- DNAStringSet(sequences)
Biostrings::reverseComplement(dna)
```

```{r}
class(dna)
```

### readDNAStringSet()

```{r}
fa_file <-
    system.file(package="Biostrings", "extdata", "dm3_upstream2000.fa.gz")
readLines(fa_file, 5)

# tail(readLines(fa_file, 44), 5)
```

```{r}
dna <- readDNAStringSet(fa_file)
dna
```

## letterFrequency(): calculate GC content

```{r}
# letterFrequency()

gc_cont <- letterFrequency(dna, "GC", as.prob = TRUE)
plot(gc_cont)
```

### Tidy Bioconductor 

```{r}
gc <- dna %>%
        letterFrequency("GC", as.prob = TRUE) %>% tibble::as_tibble() 
gc 
```

```{r}
mean_narm <- function(...) {
    mean(... , na.rm = TRUE)
} # the "..." means that it will accept any parameter
```

```{r}
sessionInfo()
```
